"""
Mock employee performance data.
Exactly 2 employees have edge-case conflicts for AI review:
  E05 (Emma)  — high volume + low quality → AI should suggest At Risk / PIP
  E06 (Farid) — slow but excellent quality → AI should suggest Raise / Promote
"""

EMPLOYEES = [
    {
        "employee_id": "E01",
        "name": "Alice Tan",
        "role": "Developer",
        "tasks_completed": 130,
        "on_time_rate": 0.93,
        "quality_score": 4.7,
        "kpi_score": 0.96,
        "collaboration": 4.5,
        "attendance": 0.98,
        "prev_quality_score": 4.5,
        "prev_on_time_rate": 0.91,
    },
    {
        "employee_id": "E02",
        "name": "Bob Lim",
        "role": "Developer",
        "tasks_completed": 90,
        "on_time_rate": 0.76,
        "quality_score": 3.7,
        "kpi_score": 0.72,
        "collaboration": 3.8,
        "attendance": 0.90,
        "prev_quality_score": 3.6,
        "prev_on_time_rate": 0.74,
    },
    {
        "employee_id": "E03",
        "name": "Carol Ng",
        "role": "Designer",
        "tasks_completed": 100,
        "on_time_rate": 0.89,
        "quality_score": 4.3,
        "kpi_score": 0.86,
        "collaboration": 4.2,
        "attendance": 0.97,
        "prev_quality_score": 4.2,
        "prev_on_time_rate": 0.87,
    },
    {
        "employee_id": "E04",
        "name": "David Lee",
        "role": "Manager",
        "tasks_completed": 70,
        "on_time_rate": 0.91,
        "quality_score": 4.8,
        "kpi_score": 0.94,
        "collaboration": 4.2,
        "attendance": 0.99,
        "prev_quality_score": 4.7,
        "prev_on_time_rate": 0.89,
    },
    {
        # EDGE CASE → AI should suggest: At Risk / PIP
        # Highest tasks but terrible quality + collaboration, declining quality
        "employee_id": "E05",
        "name": "Emma Soh",
        "role": "Developer",
        "tasks_completed": 140,
        "on_time_rate": 0.95,
        "quality_score": 2.9,
        "kpi_score": 0.88,
        "collaboration": 2.5,
        "attendance": 0.96,
        "prev_quality_score": 3.2,
        "prev_on_time_rate": 0.91,
    },
    {
        # EDGE CASE → AI should suggest: Raise / Promote
        # Slow delivery but exceptional quality work
        "employee_id": "E06",
        "name": "Farid Ali",
        "role": "Analyst",
        "tasks_completed": 75,
        "on_time_rate": 0.55,
        "quality_score": 4.5,
        "kpi_score": 0.65,
        "collaboration": 4.3,
        "attendance": 0.82,
        "prev_quality_score": 4.4,
        "prev_on_time_rate": 0.53,
    },
    {
        "employee_id": "E07",
        "name": "Grace Wu",
        "role": "Designer",
        "tasks_completed": 95,
        "on_time_rate": 0.85,
        "quality_score": 4.1,
        "kpi_score": 0.82,
        "collaboration": 4.0,
        "attendance": 0.95,
        "prev_quality_score": 3.9,
        "prev_on_time_rate": 0.83,
    },
    {
        "employee_id": "E08",
        "name": "Harry Ong",
        "role": "Developer",
        "tasks_completed": 80,
        "on_time_rate": 0.80,
        "quality_score": 3.5,
        "kpi_score": 0.73,
        "collaboration": 3.4,
        "attendance": 0.90,
        "prev_quality_score": 3.4,
        "prev_on_time_rate": 0.78,
    },
    {
        "employee_id": "E09",
        "name": "Irene Koh",
        "role": "Analyst",
        "tasks_completed": 95,
        "on_time_rate": 0.87,
        "quality_score": 4.4,
        "kpi_score": 0.89,
        "collaboration": 4.2,
        "attendance": 0.96,
        "prev_quality_score": 4.3,
        "prev_on_time_rate": 0.85,
    },
    {
        "employee_id": "E10",
        "name": "James Tan",
        "role": "Manager",
        "tasks_completed": 75,
        "on_time_rate": 0.82,
        "quality_score": 4.0,
        "kpi_score": 0.78,
        "collaboration": 4.2,
        "attendance": 0.94,
        "prev_quality_score": 3.9,
        "prev_on_time_rate": 0.80,
    },
]
